// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timesheet.Api.Data;

#nullable disable

namespace Timesheet.Api.Migrations
{
    [DbContext(typeof(TimesheetDbContext))]
    [Migration("20260119021101_AddTimesheetWeeklyStructure")]
    partial class AddTimesheetWeeklyStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Timesheet.Api.Models.TimesheetEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesheetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeeklyTimesheetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyTimesheetId");

                    b.ToTable("TimesheetEntries");
                });

            modelBuilder.Entity("Timesheet.Api.Models.WeeklyTimesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeeklyTimesheets");
                });

            modelBuilder.Entity("Timesheet.Api.Models.TimesheetEntry", b =>
                {
                    b.HasOne("Timesheet.Api.Models.WeeklyTimesheet", "WeeklyTimesheet")
                        .WithMany("Entries")
                        .HasForeignKey("WeeklyTimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyTimesheet");
                });

            modelBuilder.Entity("Timesheet.Api.Models.WeeklyTimesheet", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
